#file: noinspection ComposeUnknownValues
version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      


  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "#Paulinho11"
      MYSQL_DATABASE: gs_javaa
      MYSQL_USER: paulinslatt
      MYSQL_PASSWORD: "#Paulinho11"
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
